language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script:
  - rustup component add clippy
script:
  - cargo clippy
  - cargo clippy -- -D clippy::all
  - cargo clippy --all-targets --all-features -- -D clippy::all
  - cargo test